export enum UserRole {
  ATTENDEE = 'ATTENDEE',
  PHOTOGRAPHER = 'PHOTOGRAPHER',
  ADMIN = 'ADMIN'
}

export interface User {
  uid: string;
  email: string;
  role: UserRole;
  name?: string;
}

export interface EventData {
  id: string;
  name: string;
  description: string;
  coverImage: string;
  date: string;
  location: string;
  storageUsed: number; // in MB
  storageLimit: number; // in MB
  photographerCode: string;
  active: boolean;
}

export interface Photo {
  id: string;
  url: string;
  thumbnailUrl: string;
  timestamp: number;
  eventId: string;
  photographerId?: string;
  hasFaces: boolean;
  metadata?: {
    width: number;
    height: number;
    device?: string;
  };
  caption?: string; // Generated by Gemini
}

export interface MatchResult {
  photo: Photo;
  distance: number; // Lower is better match
}
